import { JobApplication } from '../backend';

interface ApplicationPDFData {
  applicantName: string;
  jobTitle: string;
  employer: string;
  appliedDate: string;
  status: string;
  skills: string[];
  applicationId: string;
}

export function useGenerateApplicationPDF() {
  const generatePDF = (data: ApplicationPDFData) => {
    const statusColors: Record<string, string> = {
      Applied: '#3B82F6',
      Shortlisted: '#F59E0B',
      Rejected: '#EF4444',
      Hired: '#10B981',
    };

    const statusColor = statusColors[data.status] || '#6B7280';

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Application Summary — ${data.jobTitle}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', sans-serif; color: #1e293b; background: #fff; padding: 40px; }
    .header { border-bottom: 3px solid #1e3a5f; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-start; }
    .logo { font-size: 22px; font-weight: 700; color: #1e3a5f; }
    .logo span { color: #0d9488; }
    .doc-title { font-size: 13px; color: #64748b; text-align: right; }
    .section { margin-bottom: 24px; }
    .section-title { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #64748b; margin-bottom: 12px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
    .field-row { display: flex; margin-bottom: 10px; }
    .field-label { font-size: 13px; font-weight: 500; color: #475569; width: 160px; flex-shrink: 0; }
    .field-value { font-size: 13px; color: #1e293b; }
    .status-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; color: white; background: ${statusColor}; }
    .skills-container { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 4px; }
    .skill-tag { background: #f1f5f9; border: 1px solid #e2e8f0; border-radius: 4px; padding: 3px 10px; font-size: 12px; color: #334155; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
    .id-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 12px 16px; font-size: 12px; color: #64748b; }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">AI <span>Job</span> Portal</div>
    <div class="doc-title">
      <div style="font-weight:600;font-size:15px;color:#1e293b;">Application Summary</div>
      <div>Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}</div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Applicant Information</div>
    <div class="field-row">
      <div class="field-label">Full Name</div>
      <div class="field-value">${data.applicantName}</div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Job Details</div>
    <div class="field-row">
      <div class="field-label">Job Title</div>
      <div class="field-value">${data.jobTitle}</div>
    </div>
    <div class="field-row">
      <div class="field-label">Employer</div>
      <div class="field-value">${data.employer}</div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Application Status</div>
    <div class="field-row">
      <div class="field-label">Applied On</div>
      <div class="field-value">${data.appliedDate}</div>
    </div>
    <div class="field-row">
      <div class="field-label">Current Status</div>
      <div class="field-value"><span class="status-badge">${data.status}</span></div>
    </div>
  </div>

  ${data.skills.length > 0 ? `
  <div class="section">
    <div class="section-title">Skills</div>
    <div class="skills-container">
      ${data.skills.map(s => `<span class="skill-tag">${s}</span>`).join('')}
    </div>
  </div>
  ` : ''}

  <div class="id-box">
    Application ID: ${data.applicationId}
  </div>

  <div class="footer">
    This document was generated by AI Job Portal &bull; For verification, contact support@aijobportal.com
  </div>

  <script>window.onload = () => window.print();</script>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, '_blank');
    if (win) {
      win.onafterprint = () => URL.revokeObjectURL(url);
    }
  };

  return { generatePDF };
}
