/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface Interview {
  'id' : string,
  'applicantId' : Principal,
  'scheduledDate' : Time,
  'jobId' : string,
  'notes' : string,
}
export interface JobApplication {
  'id' : string,
  'status' : string,
  'resume' : [] | [ExternalBlob],
  'appliedAt' : Time,
  'jobId' : string,
  'jobSeekerId' : Principal,
}
export interface JobListing {
  'id' : string,
  'title' : string,
  'jobType' : string,
  'description' : string,
  'deadline' : Time,
  'isActive' : boolean,
  'employer' : Principal,
  'salaryRange' : string,
  'requiredSkills' : Array<string>,
  'location' : string,
}
export interface JobRecommendation { 'jobId' : string, 'score' : bigint }
export interface SalaryPrediction {
  'jobCategory' : string,
  'maxSalary' : bigint,
  'minSalary' : bigint,
  'experienceYears' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SystemReport {
  'totalUsersByRole' : {
    'employers' : bigint,
    'jobSeekers' : bigint,
    'admins' : bigint,
  },
  'totalHires' : bigint,
  'totalJobs' : bigint,
  'totalApplications' : bigint,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'isApproved' : boolean,
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminRemoveJob' : ActorMethod<[string], undefined>,
  'applyForJob' : ActorMethod<[JobApplication], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteJob' : ActorMethod<[string], undefined>,
  'getActiveJobs' : ActorMethod<[], Array<JobListing>>,
  'getAllJobs' : ActorMethod<[], Array<JobListing>>,
  'getApplicationsForJob' : ActorMethod<[string], Array<JobApplication>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInterviewsScheduledByMe' : ActorMethod<[], Array<Interview>>,
  'getJobRecommendations' : ActorMethod<
    [Array<string>, string],
    Array<JobRecommendation>
  >,
  'getJobsByCategory' : ActorMethod<[string], Array<JobListing>>,
  'getMyInterviews' : ActorMethod<[], Array<Interview>>,
  'getMyJobApplications' : ActorMethod<[], Array<JobApplication>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSystemReport' : ActorMethod<[], SystemReport>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'postJob' : ActorMethod<[JobListing], undefined>,
  'predictSalary' : ActorMethod<[string, bigint], SalaryPrediction>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleInterview' : ActorMethod<[Interview], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateApplicationStatus' : ActorMethod<[string, string], undefined>,
  'updateApplicationsStatus' : ActorMethod<[Array<string>, string], undefined>,
  'updateJob' : ActorMethod<[JobListing], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];