/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const JobApplication = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'resume' : IDL.Opt(ExternalBlob),
  'appliedAt' : Time,
  'jobId' : IDL.Text,
  'jobSeekerId' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const JobListing = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'jobType' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : Time,
  'isActive' : IDL.Bool,
  'employer' : IDL.Principal,
  'salaryRange' : IDL.Text,
  'requiredSkills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'isApproved' : IDL.Bool,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Interview = IDL.Record({
  'id' : IDL.Text,
  'applicantId' : IDL.Principal,
  'scheduledDate' : Time,
  'jobId' : IDL.Text,
  'notes' : IDL.Text,
});
export const JobRecommendation = IDL.Record({
  'jobId' : IDL.Text,
  'score' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SystemReport = IDL.Record({
  'totalUsersByRole' : IDL.Record({
    'employers' : IDL.Nat,
    'jobSeekers' : IDL.Nat,
    'admins' : IDL.Nat,
  }),
  'totalHires' : IDL.Nat,
  'totalJobs' : IDL.Nat,
  'totalApplications' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const SalaryPrediction = IDL.Record({
  'jobCategory' : IDL.Text,
  'maxSalary' : IDL.Nat,
  'minSalary' : IDL.Nat,
  'experienceYears' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminRemoveJob' : IDL.Func([IDL.Text], [], []),
  'applyForJob' : IDL.Func([JobApplication], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteJob' : IDL.Func([IDL.Text], [], []),
  'getActiveJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getAllJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getApplicationsForJob' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInterviewsScheduledByMe' : IDL.Func([], [IDL.Vec(Interview)], ['query']),
  'getJobRecommendations' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Vec(JobRecommendation)],
      ['query'],
    ),
  'getJobsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(JobListing)], ['query']),
  'getMyInterviews' : IDL.Func([], [IDL.Vec(Interview)], ['query']),
  'getMyJobApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSystemReport' : IDL.Func([], [SystemReport], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'postJob' : IDL.Func([JobListing], [], []),
  'predictSalary' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [SalaryPrediction],
      ['query'],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleInterview' : IDL.Func([Interview], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateApplicationStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateApplicationsStatus' : IDL.Func([IDL.Vec(IDL.Text), IDL.Text], [], []),
  'updateJob' : IDL.Func([JobListing], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const JobApplication = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'resume' : IDL.Opt(ExternalBlob),
    'appliedAt' : Time,
    'jobId' : IDL.Text,
    'jobSeekerId' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const JobListing = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'jobType' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : Time,
    'isActive' : IDL.Bool,
    'employer' : IDL.Principal,
    'salaryRange' : IDL.Text,
    'requiredSkills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'isApproved' : IDL.Bool,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const Interview = IDL.Record({
    'id' : IDL.Text,
    'applicantId' : IDL.Principal,
    'scheduledDate' : Time,
    'jobId' : IDL.Text,
    'notes' : IDL.Text,
  });
  const JobRecommendation = IDL.Record({
    'jobId' : IDL.Text,
    'score' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SystemReport = IDL.Record({
    'totalUsersByRole' : IDL.Record({
      'employers' : IDL.Nat,
      'jobSeekers' : IDL.Nat,
      'admins' : IDL.Nat,
    }),
    'totalHires' : IDL.Nat,
    'totalJobs' : IDL.Nat,
    'totalApplications' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const SalaryPrediction = IDL.Record({
    'jobCategory' : IDL.Text,
    'maxSalary' : IDL.Nat,
    'minSalary' : IDL.Nat,
    'experienceYears' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminRemoveJob' : IDL.Func([IDL.Text], [], []),
    'applyForJob' : IDL.Func([JobApplication], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteJob' : IDL.Func([IDL.Text], [], []),
    'getActiveJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getAllJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getApplicationsForJob' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInterviewsScheduledByMe' : IDL.Func(
        [],
        [IDL.Vec(Interview)],
        ['query'],
      ),
    'getJobRecommendations' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Vec(JobRecommendation)],
        ['query'],
      ),
    'getJobsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getMyInterviews' : IDL.Func([], [IDL.Vec(Interview)], ['query']),
    'getMyJobApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSystemReport' : IDL.Func([], [SystemReport], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'postJob' : IDL.Func([JobListing], [], []),
    'predictSalary' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [SalaryPrediction],
        ['query'],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleInterview' : IDL.Func([Interview], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateApplicationStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateApplicationsStatus' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'updateJob' : IDL.Func([JobListing], [], []),
  });
};

export const init = ({ IDL }) => { return []; };